"""
Wolfclaw V3 — Export & Reports API Routes (Phase 15)

Generate professional PDF and DOCX reports from chat conversations.
"""

import os
import io
import json
import uuid
from datetime import datetime
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List, Optional

router = APIRouter(prefix="/reports", tags=["Reports"])


class ChatMessageExport(BaseModel):
    role: str
    content: str

class ExportRequest(BaseModel):
    bot_name: str = "AI Bot"
    messages: List[ChatMessageExport]
    title: Optional[str] = None


# ─────────── PDF EXPORT ───────────

@router.post("/pdf")
async def export_chat_to_pdf(req: ExportRequest):
    """Generate a PDF from chat messages."""
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.units import inch
        from reportlab.lib.enums import TA_LEFT, TA_RIGHT
    except ImportError:
        raise HTTPException(status_code=500, detail="reportlab is not installed. Run: pip install reportlab")

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'ChatTitle', parent=styles['Title'],
        fontSize=18, textColor=HexColor('#1a1a2e'),
        spaceAfter=12
    )
    meta_style = ParagraphStyle(
        'ChatMeta', parent=styles['Normal'],
        fontSize=9, textColor=HexColor('#888888'),
        spaceAfter=20
    )
    user_style = ParagraphStyle(
        'UserMsg', parent=styles['Normal'],
        fontSize=10, textColor=HexColor('#1a1a2e'),
        leftIndent=40, spaceAfter=8,
        backColor=HexColor('#e8f4f8'),
        borderPadding=8
    )
    assistant_style = ParagraphStyle(
        'AssistantMsg', parent=styles['Normal'],
        fontSize=10, textColor=HexColor('#333333'),
        spaceAfter=8, borderPadding=8
    )
    role_style = ParagraphStyle(
        'RoleLabel', parent=styles['Normal'],
        fontSize=8, textColor=HexColor('#666666'),
        spaceAfter=2
    )

    elements = []

    # Title
    title = req.title or f"Chat with {req.bot_name}"
    elements.append(Paragraph(title, title_style))
    elements.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')} • {len(req.messages)} messages",
        meta_style
    ))

    # Messages
    for msg in req.messages:
        role_label = "👤 You" if msg.role == "user" else f"🤖 {req.bot_name}"
        style = user_style if msg.role == "user" else assistant_style

        elements.append(Paragraph(f"<b>{role_label}</b>", role_style))

        # Clean content for PDF (escape XML chars)
        content = msg.content.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
        content = content.replace('\n', '<br/>')

        elements.append(Paragraph(content, style))
        elements.append(Spacer(1, 6))

    # Footer
    footer_style = ParagraphStyle(
        'Footer', parent=styles['Normal'],
        fontSize=8, textColor=HexColor('#aaaaaa'),
        spaceBefore=30
    )
    elements.append(Paragraph("— Generated by Wolfclaw AI —", footer_style))

    doc.build(elements)
    buffer.seek(0)

    filename = f"wolfclaw_chat_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


# ─────────── DOCX EXPORT ───────────

@router.post("/docx")
async def export_chat_to_docx(req: ExportRequest):
    """Generate a DOCX from chat messages."""
    try:
        from docx import Document
        from docx.shared import Pt, Inches, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError:
        raise HTTPException(status_code=500, detail="python-docx is not installed. Run: pip install python-docx")

    doc = Document()

    # Title
    title = req.title or f"Chat with {req.bot_name}"
    heading = doc.add_heading(title, level=1)
    heading.runs[0].font.color.rgb = RGBColor(0x1a, 0x1a, 0x2e)

    # Metadata
    meta = doc.add_paragraph()
    meta_run = meta.add_run(f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')} • {len(req.messages)} messages")
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.add_paragraph()  # spacer

    # Messages
    for msg in req.messages:
        role_label = "👤 You" if msg.role == "user" else f"🤖 {req.bot_name}"

        # Role header
        role_para = doc.add_paragraph()
        role_run = role_para.add_run(role_label)
        role_run.bold = True
        role_run.font.size = Pt(10)
        role_run.font.color.rgb = RGBColor(0x44, 0x44, 0x44) if msg.role == "user" else RGBColor(0x10, 0xb9, 0x81)

        # Message content
        content_para = doc.add_paragraph(msg.content)
        content_para.paragraph_format.space_after = Pt(8)
        for run in content_para.runs:
            run.font.size = Pt(10)

    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer_run = footer.add_run("— Generated by Wolfclaw AI —")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0xaa, 0xaa, 0xaa)
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Save to buffer
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    filename = f"wolfclaw_chat_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
